remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true
github:
  zip_url: https://github.com/SweetBoy13735/Until-25/archive/refs/tags/v1.0.0.zip
  tar_url: https://github.com/SweetBoy13735/Until-25/archive/refs/tags/v1.0.0.tar.gz
